export enum EVENTS {
  ORDER_APPROVAL_STEP_UPDATE_ORDER_STATUS = 'ORDER_APPROVAL_STEP_UPDATE_ORDER_STATUS',
  ORDER_APPROVAL_STEP_INVOICE_GENERATE = 'ORDER_APPROVAL_STEP_INVOICE_GENERATE',
  ORDER_FAILED = 'ORDER_FAILED'
}
