export enum EVENTS {
  USER_CREATED = 'USER_CREATED',
  USER_UPDATED = 'USER_UPDATED',
  USER_PASSWORD_UPDATED = 'USER_PASSWORD_UPDATED',
  USER_DELETED = 'USER_DELETED',
  ORDER_CREATED = 'ORDER_CREATED',
  INVOICE_CREATED = 'INVOICE_CREATED',
  ORDER_APPROVED = 'ORDER_APPROVED',
  ORDER_CANCELED = 'ORDER_CANCELED'
}
