export enum Variables {
  REDIS = 'REDIS',
  REDIS_SERVICE = 'REDIS_SERVICE',
  REDIS_HOST = 'REDIS_HOST',
  REDIS_PORT = 'REDIS_PORT',
  REDIS_PASSWORD = 'REDIS_PASSWORD',
  RABBIT_MQ = 'RABBIT_MQ',
  RABBITMQ_URL = 'RABBITMQ_URL',
  RABBIT_MQ_SERVICE = 'RABBIT_MQ_SERVICE',
};
